project_id = "zbcnepczdenymvfeuoaj"

[functions.check-user-type]
verify_jwt = false

[functions.wati-whatsapp]
verify_jwt = false

[functions.vendor-action]
verify_jwt = false

[functions.zoho-crm]
verify_jwt = false

[functions.dashboard-chat]
verify_jwt = false

[functions.zoho-crm-inventory]
verify_jwt = false

[functions.zoho-crm-requests]
verify_jwt = false

[functions.wati-vendor-reminder]
verify_jwt = false

[functions.wati-service-confirmation]
verify_jwt = false

[functions.wati-rental-confirmation]
verify_jwt = false
