project_id = "zbcnepczdenymvfeuoaj"

[functions.check-user-type]
verify_jwt = false

[functions.vendor-action]
verify_jwt = false

[functions.zoho-crm]
verify_jwt = false

[functions.dashboard-chat]
verify_jwt = false

[functions.zoho-crm-inventory]
verify_jwt = false

[functions.zoho-crm-requests]
verify_jwt = false

[functions.sync-quote-to-order]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.notify-admin-order]
verify_jwt = false

[functions.milestone-reminder]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.scan-chat-image]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
