-- Update About content with comprehensive Avens information
UPDATE about_content SET 
  founder_name = 'Mr. A. Venkateshwar',
  founder_quote = 'Events possess an incredible power to unite people, ignite action, and etch unforgettable memories into our hearts. At Avens, we don''t merely construct events — we craft experiences that weave stories, honor milestones, and forge history with fervor and passion.',
  founder_note = 'Mr. Venkateshwar, a visionary entrepreneur with over two decades of industry experience, founded Avens with a steadfast belief that events transcend mere logistical endeavors. He envisioned them as transformative experiences that foster connections between individuals, ideas, and emotions. Despite commencing with limited resources and boundless enthusiasm, Mr. Venkateshwar meticulously constructed Avens into a reputable brand that seamlessly integrates creativity, technology, and precision. His leadership is characterized by resilience, innovation, and an exceptional capacity to perform under pressure—qualities that have enabled Avens to successfully execute some of India''s most intricate government and corporate events.',
  mission_statement = 'To transform visions into reality by providing innovative, reliable, and scalable event management and rental solutions, ensuring every event — big or small — is delivered with passion, precision, and purpose.',
  vision_statement = 'To become India''s most trusted event infrastructure and management company, we are committed to setting unparalleled benchmarks in quality, creativity, and execution. Our vision is to expand globally, passionately redefining how events are experienced worldwide.',
  full_about_text = 'Avens Expositions Pvt. Ltd. was established in 2006 with a singular objective: to revolutionize the construction and experiential aspects of events in India. Based in Hyderabad, we have evolved from a modest event service provider into a nationally acclaimed brand specializing in world-class event management and rental infrastructure. For over a decade, Avens has consistently delivered exceptional experiences across a diverse range of events, including corporate exhibitions, government summits, medical conferences, weddings, cultural festivals, lifestyle shows, and sporting events. From intimate gatherings to expansive expos spanning millions of square feet, our unwavering commitment remains: seamless execution, premium quality, and unforgettable experiences. What distinguishes us is not solely our infrastructure but our mindset. With in-house inventories such as German aluminum hangars (ranging from 20m to 50m spans), industrial air-conditioning solutions (Airwingz), customized exhibition stalls, pagodas, décor, staging, and audio-visual equipment, we exert control over quality, speed, and cost—providing our clients with the confidence to envision ambitious projects. Over the years, we have proudly collaborated with esteemed organizations such as CII, FICCI, ASSOCHAM, the Government of Telangana, the Government of Andhra Pradesh, and numerous corporates, NGOs, and private clients. Our work has been featured in international expos, medical summits, aero shows, and prestigious cultural events, solidifying our reputation as one of South India''s leading event infrastructure companies.',
  updated_at = now()
WHERE id = (SELECT id FROM about_content LIMIT 1);

-- Clear existing team members and insert new Avens team structure
DELETE FROM team_members;

INSERT INTO team_members (name, role, short_bio, full_bio, display_order, is_active) VALUES
('Mr. A. Venkateshwar', 'Founder & Managing Director', 'Visionary leader who built Avens Expositions from the ground up. Oversees company strategy, client trust, and innovation in event infrastructure.', 'Visionary leader with over two decades of experience who founded Avens Expositions with a belief that events transcend logistics to create transformative experiences. Oversees strategic direction, client relationships, and drives innovation in event infrastructure solutions.', 1, true),
('Director', 'Director', 'Drives business growth, partnerships, and ensures financial and operational stability of the organization.', 'Strategic leader responsible for business development, key partnerships, and maintaining financial and operational excellence across all divisions of Avens Expositions.', 2, true),
('General Manager', 'General Manager – Operations', 'Manages day-to-day operations, ensuring smooth coordination between departments and timely project execution.', 'Experienced operations leader who ensures seamless coordination between all departments, manages project timelines, and maintains operational excellence across all events and initiatives.', 3, true),
('Event Manager', 'Event Manager', 'Responsible for planning, organizing, and executing events while ensuring client satisfaction and seamless experiences.', 'Dedicated event professional specializing in end-to-end event planning and execution, ensuring every client receives exceptional service and unforgettable experiences.', 4, true),
('Project Manager', 'Project Manager', 'Leads individual event projects, manages budgets, timelines, and coordinates on-site operations.', 'Detail-oriented project leader who manages event budgets, coordinates timelines, and oversees on-site operations to ensure flawless event delivery within scope and budget.', 5, true),
('Creative Director', 'Creative Director', 'Heads the design and branding team, developing innovative concepts for décor, stalls, and visual identity.', 'Artistic visionary leading the creative team in developing innovative design concepts, branding strategies, and visual identities that bring client visions to life.', 6, true),
('Technical Head', 'Technical Head (AV & Infrastructure)', 'Oversees audio-visual, lighting, air-conditioning, and technical solutions for all events.', 'Technical expert managing all audio-visual systems, lighting solutions, infrastructure setups, and innovative technical solutions that power world-class events.', 7, true),
('Site Manager', 'Site Managers', 'On-ground leaders who supervise setup, safety, and vendor coordination during events.', 'Field leaders responsible for on-site event execution, safety protocols, vendor coordination, and ensuring all technical and logistical elements work seamlessly.', 8, true),
('Logistics Manager', 'Logistics & Warehouse Manager', 'Handles transportation, storage, and inventory of event structures, ACs, stalls, and décor.', 'Operations specialist managing transportation logistics, warehouse operations, and inventory of premium event equipment including structures, ACs, and décor elements.', 9, true),
('Client Relations Manager', 'Client Relations Manager', 'Main point of contact for clients, ensuring clear communication and satisfaction throughout the project.', 'Client-focused professional serving as the primary liaison between clients and internal teams, ensuring clear communication and exceptional satisfaction throughout every project.', 10, true),
('Business Development Executive', 'Business Development Executives', 'Expand client base, manage partnerships, and bring in new business opportunities.', 'Growth-oriented professionals focused on expanding the client base, developing strategic partnerships, and identifying new business opportunities in the event management sector.', 11, true);

-- Update premium equipment rentals with Avens categories
DELETE FROM rentals;

INSERT INTO rentals (title, description, short_description, price_range, categories, image_urls, search_keywords, show_on_home, is_active, display_order) VALUES

-- Mega Event Structures
('German Aluminum Hangars (20m-50m spans)', 'World-class, durable structures ideal for large-scale exhibitions, government programs, and mega weddings. Quick installation and 100% safety compliance with spans ranging from 20m to 50m.', 'Durable German aluminum structures for large-scale events', 'Premium Pricing', ARRAY['Mega Event Structures', 'Hangars'], ARRAY[]::text[], 'german aluminum hangar exhibition structure large scale', true, true, 1),

('Dome Tents & Customized Structures', 'Iconic geodesic domes and custom-engineered tents for luxury, lifestyle, and international-standard events. Perfect for creating unique and memorable event spaces.', 'Custom geodesic domes and luxury event tents', 'Premium Pricing', ARRAY['Mega Event Structures', 'Domes'], ARRAY[]::text[], 'dome tent geodesic custom structure luxury', true, true, 2),

('Waterproof All-Weather Structures', 'Heavy-duty structures designed to withstand wind, rain, and tough outdoor conditions. Ideal for outdoor events requiring reliable weather protection.', 'Weather-resistant structures for outdoor events', 'Premium Pricing', ARRAY['Mega Event Structures', 'Weather Protection'], ARRAY[]::text[], 'waterproof weather resistant outdoor structure', true, true, 3),

-- Climate Control & Power Solutions
('Airwingz Industrial Air Conditioners (15TR & above)', 'Premium event ACs for large venues, with intelligent temperature control, quick 5-hour installation, and energy efficiency. Capacity from 15TR and above.', 'Industrial AC units for large venue climate control', 'Premium Pricing', ARRAY['Climate Control', 'Air Conditioning'], ARRAY[]::text[], 'airwingz industrial AC air conditioner temperature control', true, true, 4),

('Chiller Units (Up to 3000 Tons)', 'Massive cooling capacity for mega exhibitions, defense expos, and hangar setups. Industrial-grade chillers providing reliable temperature control for large spaces.', 'High-capacity chiller units for mega events', 'Premium Pricing', ARRAY['Climate Control', 'Chillers'], ARRAY[]::text[], 'chiller unit cooling capacity mega exhibition', true, true, 5),

('Power Generators (Silent, High-Capacity)', 'Reliable power backup for exhibitions, government shows, and concerts — ensuring uninterrupted performance with silent operation and high capacity output.', 'Silent high-capacity generators for event power', 'Premium Pricing', ARRAY['Power Solutions', 'Generators'], ARRAY[]::text[], 'generator power backup silent high capacity', true, true, 6),

-- Exhibition & Expo Infrastructure
('Maxima Stalls', 'Sleek, modular exhibition stall systems designed for international expos and trade fairs. Professional appearance with flexible configuration options.', 'Premium modular exhibition stall systems', 'Premium Pricing', ARRAY['Exhibition Infrastructure', 'Stalls'], ARRAY[]::text[], 'maxima stall exhibition expo trade fair', true, true, 7),

('Octanorm Stalls (Premium Configurations)', 'Cost-effective yet professional expo booths, customizable with branding. Perfect for trade shows and corporate exhibitions.', 'Professional customizable expo booth systems', 'Mid-Range Pricing', ARRAY['Exhibition Infrastructure', 'Stalls'], ARRAY[]::text[], 'octanorm stall expo booth trade show', true, true, 8),

('Customized Luxury Stalls & Pavilions', 'High-end tailor-made exhibition booths for pharma, auto, defense, and lifestyle expos. Fully customized to brand specifications and requirements.', 'Luxury custom-designed exhibition pavilions', 'Premium Pricing', ARRAY['Exhibition Infrastructure', 'Luxury Stalls'], ARRAY[]::text[], 'luxury custom stall pavilion exhibition booth', true, true, 9),

-- High-End AV & Staging
('LED Video Walls (Indoor & Outdoor)', 'Giant high-resolution LED screens for branding, live streaming, and visual impact. Available in both indoor and outdoor configurations.', 'High-resolution LED display walls for events', 'Premium Pricing', ARRAY['Audio Visual', 'LED Displays'], ARRAY[]::text[], 'LED video wall screen display branding', true, true, 10),

('Professional Concert-Grade Sound Systems', 'High-output systems for mega concerts, rallies, and international events. Professional audio equipment ensuring crystal-clear sound quality.', 'Concert-grade professional sound systems', 'Premium Pricing', ARRAY['Audio Visual', 'Sound Systems'], ARRAY[]::text[], 'concert sound system audio professional', true, true, 11),

('Advanced Lighting Rigs', 'Large-scale stage lighting, spotlights, and intelligent lighting for exhibitions, concerts, and shows. Professional lighting solutions for any event scale.', 'Professional stage and event lighting systems', 'Premium Pricing', ARRAY['Audio Visual', 'Lighting'], ARRAY[]::text[], 'stage lighting rig spotlight intelligent', true, true, 12),

('Special Effects (Lasers, Pyro, Fog Machines)', 'Premium stage effects to elevate entertainment and high-profile events. Professional special effects equipment for memorable experiences.', 'Professional special effects for premium events', 'Premium Pricing', ARRAY['Audio Visual', 'Special Effects'], ARRAY[]::text[], 'special effects laser pyro fog machine', true, true, 13),

-- Specialized Premium Rentals
('Portable Dome / Luxury Lounges', 'VIP-ready lounges with premium finishes for dignitaries and corporate guests. Elegant and comfortable spaces for high-profile attendees.', 'VIP luxury lounges for dignitaries and guests', 'Premium Pricing', ARRAY['Specialized Rentals', 'VIP Lounges'], ARRAY[]::text[], 'luxury lounge VIP portable dome dignitary', true, true, 14),

('Portable AC Lounges / Green Rooms', 'Climate-controlled green rooms and lounges for artists, VIPs, and leadership teams. Comfortable retreat spaces with temperature control.', 'Climate-controlled green rooms and VIP areas', 'Premium Pricing', ARRAY['Specialized Rentals', 'Green Rooms'], ARRAY[]::text[], 'AC lounge green room VIP climate control', true, true, 15),

('Custom Stage Platforms (Mega-Scale)', 'Engineered staging systems for large crowds, award shows, and cultural events. Professional platforms designed for spectacular performances.', 'Large-scale custom stage platforms for events', 'Premium Pricing', ARRAY['Specialized Rentals', 'Staging'], ARRAY[]::text[], 'custom stage platform mega scale performance', true, true, 16);