-- Clear existing team members and add event industry data
DELETE FROM public.team_members;

INSERT INTO public.team_members (name, role, short_bio, full_bio, display_order) VALUES
('Alexander Rivera', 'Chief Executive Officer & Creative Director', 'Visionary leader with 15+ years in luxury event design, specializing in transforming dreams into extraordinary experiences.', 'Alexander brings over 15 years of experience in luxury event planning and creative design. He has orchestrated high-profile weddings, corporate galas, and exclusive celebrations for celebrities and Fortune 500 companies.', 1),
('Sophia Martinez', 'Senior Event Coordinator & Wedding Specialist', 'Award-winning wedding planner who has coordinated over 300 celebrations, from intimate ceremonies to grand destination weddings.', 'Sophia is a certified wedding planner with a passion for creating personalized celebrations. She specializes in destination weddings and has planned events across 20+ countries.', 2),
('James Thompson', 'Corporate Events Manager & Logistics Expert', 'Corporate event specialist managing conferences, product launches, and executive retreats for global companies and government organizations.', 'James oversees all corporate and government events with his extensive background in project management and logistics. He holds a PMP certification and has managed events for up to 10,000 attendees.', 3),
('Isabella Wong', 'Design Director & Styling Consultant', 'Creative genius behind stunning event aesthetics, specializing in floral design, lighting concepts, and immersive environment creation.', 'Isabella is an internationally trained floral designer and styling expert who brings artistic vision to every event. She studied at the London Flower School and has worked with luxury brands.', 4),
('Marcus Johnson', 'Operations Manager & Vendor Relations', 'Logistics mastermind ensuring seamless event execution through strategic vendor partnerships and efficient resource management.', 'Marcus handles all operational aspects of event planning, from vendor coordination to timeline management. With a background in supply chain management, he has developed an extensive network of trusted suppliers.', 5),
('Aria Patel', 'Marketing Director & Client Relations', 'Strategic marketing professional focused on brand storytelling and building lasting relationships with clients and industry partners.', 'Aria drives the company marketing initiatives and maintains our strong client relationships. With an MBA in Marketing and experience in luxury brand management, she understands how to position events as premium experiences.', 6);