-- Seed additional venue and crew categories from WedMeGood scrape
INSERT INTO public.rentals (title, short_description, description, service_type, categories, is_active, show_on_home, image_url, price_value, pricing_unit, rating, address)
VALUES
  ('Marriage Gardens & Lawns', 'Beautiful garden and lawn venues', 'Lush green gardens and manicured lawns perfect for outdoor weddings and celebrations under the stars.', 'venue', ARRAY['Marriage Gardens'], true, true, 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600', 45000, 'Per Event', 4.4, 'Hyderabad'),
  ('Destination Wedding Venues', 'Exotic destination wedding locations', 'Breathtaking destination venues for couples who dream of a wedding getaway.', 'venue', ARRAY['Destination Venues'], true, true, 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600', 300000, 'Per Event', 4.9, 'Hyderabad'),
  ('Kalyana Mandapams', 'Traditional wedding halls', 'Spacious traditional mandapams with all amenities for Hindu weddings and ceremonies.', 'venue', ARRAY['Kalyana Mandapams'], true, true, 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=600', 30000, 'Per Event', 4.2, 'Hyderabad'),
  ('Wedding Planners', 'End-to-end wedding planning', 'Full-service wedding planners handling everything from concept to execution for a stress-free celebration.', 'crew', ARRAY['Wedding Planners'], true, true, 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=600', 75000, 'Per Event', 4.8, 'Hyderabad'),
  ('Bartenders', 'Professional bartending services', 'Expert mixologists and bartenders for cocktail parties, receptions, and bar services at events.', 'crew', ARRAY['Bartenders'], true, true, 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600', 15000, 'Per Event', 4.3, 'Hyderabad'),
  ('Wedding Entertainment', 'Live performers and acts', 'Unique entertainment acts including magicians, fire dancers, bands, and cultural performers.', 'crew', ARRAY['Entertainment'], true, true, 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=600', 25000, 'Per Event', 4.5, 'Hyderabad'),
  ('Pandits & Priests', 'Religious ceremony officiators', 'Experienced pandits and priests for performing traditional wedding ceremonies and religious rituals.', 'crew', ARRAY['Pandits'], true, true, 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?w=600', 5000, 'Per Event', 4.6, 'Hyderabad'),
  ('Invitation Designers', 'Custom wedding invitations', 'Creative invitation designers crafting beautiful custom cards, e-invites, and wedding stationery.', 'crew', ARRAY['Invitations'], true, true, 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=600', 8000, 'Per Event', 4.4, 'Hyderabad')
ON CONFLICT DO NOTHING;